### ISSUE TITLE
[storage] Object Spec and Status

### ISSUE THREAD

**Issue by glimchb** [opiproject/opi-api#180]
https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/

**Comment by jainvipin** [comment]
I think we move to keep configurable fields (i.e. user intent) in spec and system information i.e. read-only (FYI) fields in status. This allows clear ownership of fields - what user wants vs. what system delivered or what system wants user to know. A good example is how Kuberenetes leverages this categorization (more at https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/0.

As an immediate benefit, this will allow us to keep some fields that user can benefit from but we are excluding them from object definitions because we think they should not user configurable (e.g. allocated fields such as MAC OUI of the NIC, or pcie bus/slot information vs. VF/PF in PCIE identifier).

Separating spec and status fields has other benefits too:
1. It can allow operationalize (by reading status fields, you don't need a separate get response, just fetching the object can tell you its status
2. It allows building (or leveraging) tools that can look at these objects generically e.g. help with backing up the intent and restoring information (upon failure, say)
3. This can allow for a clean separation and allow us to expose Status only objects that are useful to the user (no user intent)
4. Finally having Status doesn't mean we must have something in there, if there is no operational state of an object, there is no need to have its status.

Would love to hear others' opinions on this topic. I would happy to submit a PR with relevant status fields for storage objects to keep it concrete.

**Comment by benlwalker** [comment]
@jainvipin Sounds great - let's get the input and the output separated. I think that will help a lot with clarity.
